language: c

sudo: false

env:
  global:
    - RACKET_DIR=cache/racket
  matrix:
    - RACKET_VERSION=5.3.5
    - RACKET_VERSION=5.92
    - RACKET_VERSION=6.0
    - RACKET_VERSION=6.1
    - RACKET_VERSION=6.1.1
    - RACKET_VERSION=HEAD

matrix:
  allow_failures:
    - env: RACKET_VERSION=HEAD
  fast_finish: true

addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    
cache:
  apt: true
  directories:
  - bin/cover
  - cache
  - cache/racket  # Matches RACKET_DIR
  
before_install:
  - . scripts/get_racket.sh
  - alias racket='$RACKET_DIR/bin/racket'

before_script:
  - make testdepend
  - wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz
  - tar xzf master.tar.gz && mkdir kcov-master/build
  - cd kcov-master/build && cmake .. && make
  - cd ../.. && mkdir coverage
  
script:
  - kcov-master/build/src/kcov --coveralls-id=$TRAVIS_JOB_ID coverage scripts/run_tests.sh

after_success: coveralls
