language: ruby

sudo: false

rvm:
  - ruby-head-clang
  - ruby-head
  - ruby-2.2.1-clang
  - ruby-2.2.1
  - ruby-2.2.0-rc1

env:
  global:
    - RACKET_DIR=~/racket
  matrix:
    - RACKET_VERSION=5.3.4
    - RACKET_VERSION=5.3.5
    - RACKET_VERSION=5.92
    - RACKET_VERSION=6.0
    - RACKET_VERSION=6.1
    - RACKET_VERSION=6.1.1
    - RACKET_VERSION=HEAD

matrix:
  allow_failures:
    - env: RACKET_VERSION=HEAD
  fast_finish: true


before_install:
  - gem install bashcov
  - bundle install
  - git clone https://github.com/greghendershott/travis-racket.git
  - cat travis-racket/install-racket.sh | bash # pipe to bash not sh!
  - export PATH="${RACKET_DIR}/bin:${PATH}" #install-racket.sh can't set for us

before_script:
  - gem update
  - gem --version

script:
  - make run

after_success: coveralls
