language: c

sudo: true

env:
  global:
    - RACKET_DIR=~/racket
    - CI_NODE_TOTAL=6
  matrix:
    - RACKET_VERSION=5.3.5
    - RACKET_VERSION=5.92
    - RACKET_VERSION=6.0
    - RACKET_VERSION=6.1
    - RACKET_VERSION=6.1.1
    - RACKET_VERSION=HEAD

matrix:
  allow_failures:
    - env: RACKET_VERSION=HEAD
  fast_finish: true


before_install:
  - git clone https://github.com/greghendershott/travis-racket.git
  - cat travis-racket/install-racket.sh | bash
  - export PATH="${RACKET_DIR}/bin:${PATH}"

script:
  - make testdepend

after_success: |
  sudo apt-get install libcurl4-openssl-dev libelf-dev libdw-dev &&
  wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
  tar xzf master.tar.gz && mkdir kcov-master/build && 
  cd kcov-master/build && cmake .. && make &&
  sudo make install && cd ../.. && ls && mkdir coverage &&
  kcov --coveralls-id=$TRAVIS_JOB_ID coverage run_tests.sh && 
  coveralls

