language: ruby

sudo: false

rvm:
  - ruby-head-clang
  - ruby-head

env:
  global:
    - RACKET_DIR=~/racket
    - CI_NODE_TOTAL=6
  matrix:
    - RACKET_VERSION=5.3.4
    - RACKET_VERSION=5.3.5
    - RACKET_VERSION=5.92
    - RACKET_VERSION=6.0
    - RACKET_VERSION=6.1
    - RACKET_VERSION=6.1.1
    - RACKET_VERSION=HEAD
    - CI_NODE_INDEX=0
    - CI_NODE_INDEX=1
    - CI_NODE_INDEX=2
    - CI_NODE_INDEX=3
    - CI_NODE_INDEX=4
    - CI_NODE_INDEX=5

matrix:
  allow_failures:
    - env: RACKET_VERSION=HEAD
  fast_finish: true


before_install:
  - gem update --system
  - bundle install
  - git clone https://github.com/greghendershott/travis-racket.git
  - cat travis-racket/install-racket.sh | bash # pipe to bash not sh!
  - export PATH="${RACKET_DIR}/bin:${PATH}" #install-racket.sh can't set for us

before_script:
  - gem update
  - gem --version

script:
  - make run

after_success: coveralls
